# copyright (c) 2025 @analytics withharry
# all rights reserved.
# licensed under the mit license.

# YOLOv8 Nano Configuration for Neurova

name: yolov8n
version: 8.0.0
framework: onnx
type: detection
description: YOLOv8 Nano - Ultrafast object detector

# Model variants
variants:
  - name: yolov8n
    size: nano
    params: 3.2M
  - name: yolov8s
    size: small
    params: 11.2M
  - name: yolov8m
    size: medium
    params: 25.9M
  - name: yolov8l
    size: large
    params: 43.7M
  - name: yolov8x
    size: xlarge
    params: 68.2M

# Model files
files:
  onnx: yolov8n.onnx
  tensorrt: yolov8n.engine
  openvino_xml: yolov8n.xml
  openvino_bin: yolov8n.bin
  ncnn_param: yolov8n.param
  ncnn_bin: yolov8n.bin

# Input specification
input:
  name: images
  shape: [1, 3, 640, 640]
  dtype: float32
  format: NCHW
  color_order: RGB

  preprocessing:
    resize:
      width: 640
      height: 640
      interpolation: bilinear
      letterbox: true # Maintain aspect ratio with padding
      padding_value: 114
    normalize:
      scale: 255.0 # Divide by 255 only, no mean/std
      mean: [0.0, 0.0, 0.0]
      std: [1.0, 1.0, 1.0]

# Output specification
output:
  - name: output0
    shape: [1, 84, 8400] # [batch, 4+80, predictions]
    dtype: float32

# Detection post-processing
postprocess:
  type: yolov8
  conf_threshold: 0.25
  iou_threshold: 0.45
  max_detections: 300

  # Anchor-free detection
  strides: [8, 16, 32]

  # Box decoding
  box_format: xyxy # x1, y1, x2, y2

  # NMS parameters
  nms:
    type: batched # regular, batched, or soft
    class_agnostic: false

# Class labels
labels:
  file: coco_labels.txt
  format: text
  num_classes: 80

# Training info
training:
  dataset: COCO
  epochs: 500
  batch_size: 96
  optimizer: SGD
  lr: 0.01
  augmentation:
    - mosaic
    - mixup
    - copy_paste

# Performance benchmarks
benchmarks:
  gpu_v100:
    latency_ms: 1.5
    throughput_fps: 667
  gpu_rtx3080:
    latency_ms: 1.2
    throughput_fps: 833
  cpu_i9:
    latency_ms: 45
    throughput_fps: 22

# Hardware optimizations
optimizations:
  cuda:
    use_cudnn: true
    tensor_cores: true
    precision: fp16
  tensorrt:
    use_dla: false
    precision: fp16
    workspace_mb: 1024
  opencl:
    work_group_size: [16, 16]

# Evaluation metrics
metrics:
  coco_map: 0.373
  coco_map50: 0.527
  coco_map75: 0.403

# Metadata
metadata:
  author: Ultralytics
  license: AGPL-3.0
  paper: https://github.com/ultralytics/ultralytics
  source: ultralytics
